/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
//IMPORT
import backend.FiguraCRUD;
import com.mongodb.MongoException;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author dell
 */
public class CirculoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CirculoJPanel
     */

    private FiguraCRUD figuraDAO;
    public CirculoJPanel(FiguraCRUD figuraDAO) {
        
        if (figuraDAO != null) {
             this.figuraDAO = figuraDAO;
            initComponents();   
        }else{
         throw new IllegalArgumentException("figuraDAO no puede ser null");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        container_content1 = new javax.swing.JPanel();
        content_header1 = new javax.swing.JPanel();
        content_title1 = new javax.swing.JLabel();
        jLabelRadio = new javax.swing.JLabel();
        jTextFieldRadio = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelArea = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(600, 400));

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(30, 33, 44));
        title.setText("Circulo");

        description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description.setForeground(new java.awt.Color(51, 51, 51));
        description.setText("Este módulo calcula el area de un circulo");

        container_content1.setBackground(new java.awt.Color(255, 255, 255));
        container_content1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 244, 247), 2, true));

        content_title1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        content_title1.setText("Calcular");

        javax.swing.GroupLayout content_header1Layout = new javax.swing.GroupLayout(content_header1);
        content_header1.setLayout(content_header1Layout);
        content_header1Layout.setHorizontalGroup(
            content_header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_header1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(content_title1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        content_header1Layout.setVerticalGroup(
            content_header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_header1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_title1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabelRadio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelRadio.setText("Radio");

        jTextFieldRadio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jButtonCalcular.setBackground(new java.awt.Color(43, 105, 92));
        jButtonCalcular.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.setBorder(null);
        jButtonCalcular.setBorderPainted(false);
        jButtonCalcular.setFocusable(false);
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelEmail1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelEmail1.setText("Área: ");

        jLabelArea.setText("0.00");
        jLabelArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        // Cargar la imagen del círculo
        jLabel1 = new javax.swing.JLabel();
        java.net.URL urlCirculoG = getClass().getResource("/imagenes/Circulo_G.png");
        ImageIcon iconoCirculo = new ImageIcon(urlCirculoG);
        jLabel1.setIcon(iconoCirculo);

        jPanel2.setBackground(new java.awt.Color(2, 207, 166));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("cm^2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout container_content1Layout = new javax.swing.GroupLayout(container_content1);
        container_content1.setLayout(container_content1Layout);
        container_content1Layout.setHorizontalGroup(
            container_content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content_header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(container_content1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(container_content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(container_content1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelRadio)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(container_content1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelEmail1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        container_content1Layout.setVerticalGroup(
            container_content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_content1Layout.createSequentialGroup()
                .addComponent(content_header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(container_content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(container_content1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(container_content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRadio)
                            .addComponent(jTextFieldRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(container_content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(container_content1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelEmail1)))
                        .addGap(63, 63, 63)
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description)
                    .addComponent(title)
                    .addComponent(container_content1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container_content1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

   
    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
                  
        try {
            double radio = Double.parseDouble(jTextFieldRadio.getText());
            double area = figuraDAO.insertarCirculo(radio);
            jLabelArea.setText(String.format("%.2f", area)); 
            JOptionPane.showMessageDialog(this, "Círculo agregado correctamente a la base de datos");
            limpiarMensaje();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor numérico válido para el radio", "Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldRadio.setText("");
        } catch (MongoException e) {
            JOptionPane.showMessageDialog(this, "Error al insertar círculo en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

        
    }//GEN-LAST:event_jButtonCalcularActionPerformed
    private void limpiarMensaje() {
    new Thread(() -> {
        try {
            Thread.sleep(5000); // Esperar 5000 milisegundos (5 segundos)
            jTextFieldRadio.setText(""); 
            jLabelArea.setText("");
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel container_content1;
    private javax.swing.JPanel content_header1;
    private javax.swing.JLabel content_title1;
    private javax.swing.JLabel description;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelArea;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelRadio;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldRadio;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
