/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
//IMPORT
import backend.FiguraCRUD;
import com.mongodb.MongoException;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author dell
 */
public class CuadradoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CuadradoJPanel
     */
    private FiguraCRUD figuraDAO;
    public CuadradoJPanel(FiguraCRUD figuraDAO) {
        this.figuraDAO = figuraDAO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        container_content = new javax.swing.JPanel();
        content_header = new javax.swing.JPanel();
        content_title = new javax.swing.JLabel();
        jLabelRadio = new javax.swing.JLabel();
        jTextFieldLADO = new javax.swing.JTextField();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelArea = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();
        jLabelCuadrado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(600, 400));

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(30, 33, 44));
        title.setText("Cuadrado");

        description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description.setForeground(new java.awt.Color(51, 51, 51));
        description.setText("Este módulo calcula el área de un cuadrado");

        container_content.setBackground(new java.awt.Color(255, 255, 255));
        container_content.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 244, 247), 2, true));

        content_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        content_title.setText("Calcular");

        javax.swing.GroupLayout content_headerLayout = new javax.swing.GroupLayout(content_header);
        content_header.setLayout(content_headerLayout);
        content_headerLayout.setHorizontalGroup(
            content_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(content_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        content_headerLayout.setVerticalGroup(
            content_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_title)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabelRadio.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelRadio.setText("Lado:");

        jTextFieldLADO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jLabelEmail1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelEmail1.setText("Área: ");

        jLabelArea.setText("0.00");
        jLabelArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jButtonCrear.setBackground(new java.awt.Color(43, 105, 92));
        jButtonCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrear.setText("Calcular");
        jButtonCrear.setBorder(null);
        jButtonCrear.setBorderPainted(false);
        jButtonCrear.setFocusable(false);
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        // Cargar la imagen del cuadrado
        java.net.URL urlCuadradoG = getClass().getResource("/imagenes/Cuadrado_G.png");
        ImageIcon iconoCuadrado = new ImageIcon(urlCuadradoG);
        jLabelCuadrado.setIcon(iconoCuadrado);
        jLabelCuadrado.setPreferredSize(new java.awt.Dimension(156, 146));

        jPanel2.setBackground(new java.awt.Color(2, 207, 166));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("cm^2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout container_contentLayout = new javax.swing.GroupLayout(container_content);
        container_content.setLayout(container_contentLayout);
        container_contentLayout.setHorizontalGroup(
            container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, container_contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(container_contentLayout.createSequentialGroup()
                        .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmail1)
                            .addComponent(jLabelRadio))
                        .addGap(30, 30, 30)
                        .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLADO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );
        container_contentLayout.setVerticalGroup(
            container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_contentLayout.createSequentialGroup()
                .addComponent(content_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container_contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLADO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelEmail1))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(container_contentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title)
                    .addComponent(description))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(container_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        try {
            double lado = Double.parseDouble(jTextFieldLADO.getText());
            double area = figuraDAO.insertarCuadrado(lado);
            jLabelArea.setText(String.format("%.2f", area)); 
            JOptionPane.showMessageDialog(this, "Cuadrado agregado correctamente a la base de datos");
            limpiarMensaje();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor numérico válido para el radio", "Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldLADO.setText("");
        } catch (MongoException e) {
            JOptionPane.showMessageDialog(this, "Error al insertar círculo en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_jButtonCrearActionPerformed
    
    private void limpiarMensaje() {
    new Thread(() -> {
        try {
            Thread.sleep(5000); // Esperar 5000 milisegundos (5 segundos)
            jTextFieldLADO.setText(""); 
            jLabelArea.setText("");
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel container_content;
    private javax.swing.JPanel content_header;
    private javax.swing.JLabel content_title;
    private javax.swing.JLabel description;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelArea;
    private javax.swing.JLabel jLabelCuadrado;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelRadio;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldLADO;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
