/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.DB;
import backend.FiguraCRUD;
import com.mongodb.client.MongoDatabase;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author dell
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    private JButton botonSeleccionado;
    private DB db;
    private FiguraCRUD figuraCRUD;
    private MongoDatabase database;
    //CONFIG COLOR
    private Color defaultColorTextBoton = new Color(233, 236, 239);
    private Color defaultColorBoton = new Color(30, 33, 44);
    private Color colorSeleccion = new Color(3, 206, 164);
    private Color colorTextSeleccion = new Color(255, 255, 255);
    
    public Index() {
        db = new DB();            
        if (db.establecerConexion()) {
             database = db.getDatabase();
             figuraCRUD  = new FiguraCRUD(database);
             ListadoFiguras menu = new  ListadoFiguras(figuraCRUD);
             //figuraCRUD.insertarTriangulo(15, 18);
             //figuraCRUD.listarTriangulos();
             //figuraCRUD.eliminarColeccionCirculo();
             initComponents();
             resetBackgroundColors();
             botonSeleccionado = jButtonListar;
             botonSeleccionado.setBackground(colorSeleccion);
             botonSeleccionado.setForeground(colorTextSeleccion);
             menu.setSize(content.getWidth(),content.getHeight()); 
             System.out.println(content.getHeight()+"||"+content.getWidth());
             menu.setLocation(0, 0);
             content.removeAll();
             content.add(menu);
             content.revalidate();
             content.repaint();
            System.out.println("Conexión a la base de datos establecida");
        } else {
            System.err.println("Error al establecer la conexión a la base de datos");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        sidebar_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        subtitle_1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonCuadrado = new javax.swing.JButton();
        jButtonTriangulo = new javax.swing.JButton();
        jButtonCirculo = new javax.swing.JButton();
        subtitle_2 = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        subtitle_3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        line_buttom = new javax.swing.JPanel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        sidebar.setBackground(new java.awt.Color(30, 33, 44));

        sidebar_header.setBackground(new java.awt.Color(41, 44, 55));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DB");

        javax.swing.GroupLayout sidebar_headerLayout = new javax.swing.GroupLayout(sidebar_header);
        sidebar_header.setLayout(sidebar_headerLayout);
        sidebar_headerLayout.setHorizontalGroup(
            sidebar_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebar_headerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebar_headerLayout.setVerticalGroup(
            sidebar_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebar_headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        subtitle_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subtitle_1.setForeground(new java.awt.Color(255, 255, 255));
        subtitle_1.setText("Calcular");

        jPanel1.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jButtonCuadrado.setBackground(new java.awt.Color(30, 33, 44));
        jButtonCuadrado.setForeground(new java.awt.Color(233, 236, 239));
        jButtonCuadrado.setText("Área Cuadrado");
        jButtonCuadrado.setBorder(null);
        jButtonCuadrado.setDefaultCapable(false);
        jButtonCuadrado.setFocusPainted(false);
        jButtonCuadrado.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuadradoActionPerformed(evt);
            }
        });

        jButtonTriangulo.setBackground(new java.awt.Color(30, 33, 44));
        jButtonTriangulo.setForeground(new java.awt.Color(233, 236, 239));
        jButtonTriangulo.setText("Área Triángulo");
        jButtonTriangulo.setBorder(null);
        jButtonTriangulo.setFocusPainted(false);
        jButtonTriangulo.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrianguloActionPerformed(evt);
            }
        });

        jButtonCirculo.setBackground(new java.awt.Color(30, 33, 44));
        jButtonCirculo.setForeground(new java.awt.Color(233, 236, 239));
        jButtonCirculo.setText("Área Circulo");
        jButtonCirculo.setBorder(null);
        jButtonCirculo.setFocusPainted(false);
        jButtonCirculo.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCirculoActionPerformed(evt);
            }
        });

        subtitle_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subtitle_2.setForeground(new java.awt.Color(255, 255, 255));
        subtitle_2.setText("Ver");

        jButtonEliminar.setBackground(new java.awt.Color(30, 33, 44));
        jButtonEliminar.setForeground(new java.awt.Color(233, 236, 239));
        jButtonEliminar.setText("Eliminar datos");
        jButtonEliminar.setBorder(null);
        jButtonEliminar.setFocusPainted(false);
        jButtonEliminar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonListar.setBackground(new java.awt.Color(30, 33, 44));
        jButtonListar.setForeground(new java.awt.Color(233, 236, 239));
        jButtonListar.setText("Listado de Figuras");
        jButtonListar.setBorder(null);
        jButtonListar.setFocusPainted(false);
        jButtonListar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        subtitle_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subtitle_3.setForeground(new java.awt.Color(255, 255, 255));
        subtitle_3.setText("Vaciar");

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jButtonCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jButtonListar, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addGroup(sidebarLayout.createSequentialGroup()
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtitle_2)
                                    .addComponent(subtitle_3))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(subtitle_1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(sidebar_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(subtitle_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitle_2)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subtitle_3)
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("USER");

        line_buttom.setBackground(new java.awt.Color(33, 156, 131));

        javax.swing.GroupLayout line_buttomLayout = new javax.swing.GroupLayout(line_buttom);
        line_buttom.setLayout(line_buttomLayout);
        line_buttomLayout.setHorizontalGroup(
            line_buttomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        line_buttomLayout.setVerticalGroup(
            line_buttomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(572, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(25, 25, 25))
            .addComponent(line_buttom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(line_buttom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrianguloActionPerformed
        resetBackgroundColors();
        botonSeleccionado = jButtonTriangulo;
        botonSeleccionado.setBackground(colorSeleccion);
        botonSeleccionado.setForeground(colorTextSeleccion);
        TrianguloJPanel triangle  = new TrianguloJPanel(figuraCRUD);
        triangle.setSize(content.getWidth(),content.getHeight());
        content.setLocation(0, 0);
        content.removeAll();
        content.add(triangle);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButtonTrianguloActionPerformed

    private void jButtonCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuadradoActionPerformed
        resetBackgroundColors();
        botonSeleccionado = jButtonCuadrado;
        botonSeleccionado.setBackground(colorSeleccion);
        botonSeleccionado.setForeground(colorTextSeleccion);
        CuadradoJPanel sqrt  = new CuadradoJPanel(figuraCRUD);
        sqrt.setSize(content.getWidth(),content.getHeight());
        content.setLocation(0, 0);
        content.removeAll();
        content.add(sqrt);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButtonCuadradoActionPerformed

    private void jButtonCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCirculoActionPerformed
        resetBackgroundColors();
        botonSeleccionado = jButtonCirculo;
        botonSeleccionado.setBackground(colorSeleccion);
        botonSeleccionado.setForeground(colorTextSeleccion);
        CirculoJPanel circle  = new CirculoJPanel(figuraCRUD);
        circle.setSize(content.getWidth(),content.getHeight());
        content.setLocation(0, 0);
        content.removeAll();
        content.add(circle);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButtonCirculoActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        resetBackgroundColors();
        botonSeleccionado = jButtonListar;
        botonSeleccionado.setBackground(colorSeleccion);
        botonSeleccionado.setForeground(colorTextSeleccion);
        ListadoFiguras listado  = new ListadoFiguras(figuraCRUD);
        listado.setSize(content.getWidth(),content.getHeight());
        content.setLocation(0, 0);
        content.removeAll();
        content.add(listado);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        resetBackgroundColors();
        botonSeleccionado = jButtonEliminar;
        botonSeleccionado.setBackground(colorSeleccion);
        botonSeleccionado.setForeground(colorTextSeleccion);
        VaciarFiguras clean  = new VaciarFiguras(figuraCRUD);
        clean.setSize(content.getWidth(),content.getHeight());
        content.setLocation(0, 0);
        content.removeAll();
        content.add(clean);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_jButtonEliminarActionPerformed
    private void resetBackgroundColors() {
        //BG BOTON
        jButtonTriangulo.setBackground(defaultColorBoton);
        jButtonCuadrado.setBackground(defaultColorBoton);
        jButtonCirculo.setBackground(defaultColorBoton);
        jButtonListar.setBackground(defaultColorBoton);
        jButtonEliminar.setBackground(defaultColorBoton);
        // BG TEXT
        jButtonTriangulo.setForeground(defaultColorTextBoton);
        jButtonCuadrado.setForeground(defaultColorTextBoton);
        jButtonCirculo.setForeground(defaultColorTextBoton);
        jButtonListar.setForeground(defaultColorTextBoton);
        jButtonEliminar.setForeground(defaultColorTextBoton);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButtonCirculo;
    private javax.swing.JButton jButtonCuadrado;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel line_buttom;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel sidebar_header;
    private javax.swing.JLabel subtitle_1;
    private javax.swing.JLabel subtitle_2;
    private javax.swing.JLabel subtitle_3;
    // End of variables declaration//GEN-END:variables
}
