/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.FiguraCRUD;
import com.mongodb.MongoException;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class TrianguloJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrianguloJPanel
     */
    private FiguraCRUD figuraDAO;
    public TrianguloJPanel(FiguraCRUD figuraDAO) {
        this.figuraDAO = figuraDAO;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg3 = new javax.swing.JPanel();
        title3 = new javax.swing.JLabel();
        description3 = new javax.swing.JLabel();
        container_content3 = new javax.swing.JPanel();
        content_header3 = new javax.swing.JPanel();
        content_title3 = new javax.swing.JLabel();
        jLabelNombre3 = new javax.swing.JLabel();
        jTextFieldBase = new javax.swing.JTextField();
        jButtonCrear3 = new javax.swing.JButton();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelArea = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        bg3.setBackground(new java.awt.Color(255, 255, 255));
        bg3.setPreferredSize(new java.awt.Dimension(600, 400));

        title3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title3.setForeground(new java.awt.Color(30, 33, 44));
        title3.setText("Triángulo");

        description3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description3.setForeground(new java.awt.Color(51, 51, 51));
        description3.setText("Este módulo calcula el área de un triángulo");

        container_content3.setBackground(new java.awt.Color(255, 255, 255));
        container_content3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 244, 247), 2, true));

        content_title3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        content_title3.setText("Calcular");

        javax.swing.GroupLayout content_header3Layout = new javax.swing.GroupLayout(content_header3);
        content_header3.setLayout(content_header3Layout);
        content_header3Layout.setHorizontalGroup(
            content_header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_header3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(content_title3)
                .addContainerGap(468, Short.MAX_VALUE))
        );
        content_header3Layout.setVerticalGroup(
            content_header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_header3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_title3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabelNombre3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelNombre3.setText("Base :");

        jTextFieldBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jButtonCrear3.setBackground(new java.awt.Color(43, 105, 92));
        jButtonCrear3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrear3.setText("Calcular");
        jButtonCrear3.setBorder(null);
        jButtonCrear3.setBorderPainted(false);
        jButtonCrear3.setFocusable(false);
        jButtonCrear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrear3ActionPerformed(evt);
            }
        });

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelEmail.setText("Area : ");

        jTextFieldAltura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jLabelEmail1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelEmail1.setText("Altura :");

        jLabelArea.setText("0.00");
        jLabelArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Desktop\\POO\\Triangulo_G.png")); // NOI18N

        jPanel1.setBackground(new java.awt.Color(2, 207, 166));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("cm^2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout container_content3Layout = new javax.swing.GroupLayout(container_content3);
        container_content3.setLayout(container_content3Layout);
        container_content3Layout.setHorizontalGroup(
            container_content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_content3Layout.createSequentialGroup()
                .addGroup(container_content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content_header3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(container_content3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addGroup(container_content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre3)
                            .addComponent(jLabelEmail1)
                            .addComponent(jLabelEmail))
                        .addGap(38, 38, 38)
                        .addGroup(container_content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldBase, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(container_content3Layout.createSequentialGroup()
                                .addComponent(jLabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(container_content3Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButtonCrear3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        container_content3Layout.setVerticalGroup(
            container_content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_content3Layout.createSequentialGroup()
                .addComponent(content_header3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(container_content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container_content3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelNombre3)
                        .addGap(10, 10, 10)
                        .addComponent(jLabelEmail1)
                        .addGap(17, 17, 17)
                        .addComponent(jLabelEmail))
                    .addGroup(container_content3Layout.createSequentialGroup()
                        .addComponent(jTextFieldBase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(container_content3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonCrear3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout bg3Layout = new javax.swing.GroupLayout(bg3);
        bg3.setLayout(bg3Layout);
        bg3Layout.setHorizontalGroup(
            bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg3Layout.createSequentialGroup()
                .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(description3)
                            .addComponent(title3)))
                    .addGroup(bg3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(container_content3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        bg3Layout.setVerticalGroup(
            bg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(container_content3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(bg3, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg3, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrear3ActionPerformed
         try {
            double base = Double.parseDouble(jTextFieldBase.getText());
            double altura = Double.parseDouble(jTextFieldAltura.getText());
            double area = figuraDAO.insertarTriangulo(base, altura);
            jLabelArea.setText(String.format("%.2f", area)); 
            JOptionPane.showMessageDialog(this, "Triangulo agregado correctamente a la base de datos");
            limpiarMensaje();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un valor numérico válido para el radio", "Error", JOptionPane.ERROR_MESSAGE);
            jTextFieldBase.setText("");
        } catch (MongoException e) {
            JOptionPane.showMessageDialog(this, "Error al insertar círculo en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_jButtonCrear3ActionPerformed
    private void limpiarMensaje() {
        new Thread(() -> {
            try {
                Thread.sleep(5000); // Esperar 5000 milisegundos (5 segundos)
                jTextFieldBase.setText(""); 
                jTextFieldAltura.setText(""); 
                jLabelArea.setText("");
            } catch (InterruptedException e) {
            e.printStackTrace();
            }
        }).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg3;
    private javax.swing.JPanel container_content3;
    private javax.swing.JPanel content_header3;
    private javax.swing.JLabel content_title3;
    private javax.swing.JLabel description3;
    private javax.swing.JButton jButtonCrear3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelArea;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldBase;
    private javax.swing.JLabel title3;
    // End of variables declaration//GEN-END:variables
}
